# Случайное блуждание

__Автор задач: Блохин Н.В. (NVBlokhin@fa.ru)__

Материалы:
* Макрушин С.В. "Лекция 5: Случайные блуждания на графах"
* Документация:
    * https://networkx.org/documentation/stable/reference/generated/networkx.generators.social.karate_club_graph.html
    * https://numpy.org/doc/stable/reference/generated/numpy.diag.html
    * https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html
    * https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_power.html
    * https://numpy.org/doc/stable/reference/generated/numpy.allclose.html

## Вопросы для совместного обсуждения

1\. Обсудите понятие случайного блуждания на графах.

In [5]:
import networkx as nx

In [6]:
G = nx.karate_club_graph()

In [7]:
G.edges(data="weight")

EdgeDataView([(0, 1, 4), (0, 2, 5), (0, 3, 3), (0, 4, 3), (0, 5, 3), (0, 6, 3), (0, 7, 2), (0, 8, 2), (0, 10, 2), (0, 11, 3), (0, 12, 1), (0, 13, 3), (0, 17, 2), (0, 19, 2), (0, 21, 2), (0, 31, 2), (1, 2, 6), (1, 3, 3), (1, 7, 4), (1, 13, 5), (1, 17, 1), (1, 19, 2), (1, 21, 2), (1, 30, 2), (2, 3, 3), (2, 7, 4), (2, 8, 5), (2, 9, 1), (2, 13, 3), (2, 27, 2), (2, 28, 2), (2, 32, 2), (3, 7, 3), (3, 12, 3), (3, 13, 3), (4, 6, 2), (4, 10, 3), (5, 6, 5), (5, 10, 3), (5, 16, 3), (6, 16, 3), (8, 30, 3), (8, 32, 3), (8, 33, 4), (9, 33, 2), (13, 33, 3), (14, 32, 3), (14, 33, 2), (15, 32, 3), (15, 33, 4), (18, 32, 1), (18, 33, 2), (19, 33, 1), (20, 32, 3), (20, 33, 1), (22, 32, 2), (22, 33, 3), (23, 25, 5), (23, 27, 4), (23, 29, 3), (23, 32, 5), (23, 33, 4), (24, 25, 2), (24, 27, 3), (24, 31, 2), (25, 31, 7), (26, 29, 4), (26, 33, 2), (27, 33, 4), (28, 31, 2), (28, 33, 2), (29, 32, 4), (29, 33, 2), (30, 32, 3), (30, 33, 3), (31, 32, 4), (31, 33, 4), (32, 33, 5)])

In [8]:
A = nx.adjacency_matrix(G, weight=None).toarray()
A

array([[0, 1, 1, ..., 1, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 1, 0],
       ...,
       [1, 0, 0, ..., 0, 1, 1],
       [0, 0, 1, ..., 1, 0, 1],
       [0, 0, 0, ..., 1, 1, 0]])

In [9]:
A[0] / A[0].sum()

array([0.    , 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625,
       0.0625, 0.    , 0.0625, 0.0625, 0.0625, 0.0625, 0.    , 0.    ,
       0.    , 0.0625, 0.    , 0.0625, 0.    , 0.0625, 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.0625,
       0.    , 0.    ])

In [10]:
import numpy as np

D = np.diag([1, 2, 3, 4])
D

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Задачи для самостоятельного решения

<p class="task" id="1"></p>

1\. Загрузите граф карате-клуба. Получите матрицу смежности `A` этого графа. Получите на ее основе матрицу переходов `P` по следующему правилу:

$$\mathbf{P}=\mathbf{D}^{-1}\mathbf{A}$$

Продемонстрируйте, что выполняются условия (1) и (2).

$0 \le p_{ij} \le 1$ (1)

$\sum_j p_{ij}=1$    (2)

- [X] Проверено на семинаре

In [11]:
import networkx as nx
import numpy as np

In [12]:
G = nx.karate_club_graph()
A = nx.adjacency_matrix(G, weight=None).toarray()

In [13]:
D = np.diag(np.sum(A, axis=1))
P = np.dot(np.linalg.inv(D), A)

In [14]:
np.all((P >= 0) & (P <= 1)) # 1 условие

True

In [15]:
np.allclose(np.sum(P, axis=1), 1) # 2 условие

True

<p class="task" id="2"></p>

2\. Создайте вектор начального состояния $\mathbf{p}^0 = [0, ..., 1]^T$. Получите стационарное состояние $\mathbf{p}^\infty$, используя итеративную процедуру

$\mathbf{p}^{t+1}=(\mathbf{P}^{\top})\mathbf{p}^t$

Процесс заканчивается, когда $||\mathbf{p}^{t+1} - \mathbf{p}^{t}|| < \epsilon $

Выведите полученный вектор стационарного состояния на экран.

- [X] Проверено на семинаре

In [16]:
p_0 = np.zeros(len(G))
p_0[-1] = 1

In [17]:
p_t = p_0
p_next = np.dot(P.T, p_t)

In [18]:
e = 0.00001

In [19]:
while np.linalg.norm(p_next - p_t) >= e:
    p_t = p_next
    p_next = np.dot(P.T, p_t)

In [20]:
p_next

array([0.10253661, 0.05768442, 0.06410322, 0.038455  , 0.01922004,
       0.02562496, 0.02562496, 0.02563685, 0.03205402, 0.01282234,
       0.01922004, 0.00640828, 0.01281728, 0.03204886, 0.0128242 ,
       0.0128242 , 0.01281126, 0.01281752, 0.0128242 , 0.01922953,
       0.0128242 , 0.01281752, 0.0128242 , 0.03206145, 0.01923621,
       0.0192366 , 0.01282469, 0.02564728, 0.01923399, 0.02564947,
       0.02564434, 0.03846881, 0.07694329, 0.10900016])

<p class="task" id="3"></p>

3\. Найдите матрицу перехода к стационарному состоянию $(\mathbf{P}^{\top})^\infty$ при помощи процедуры возведения матрицы в степень.

Докажите, что полученная матрица является матрицей стационарного состояния, т.е. $||(\mathbf{P}^{\top})^{\infty}  -(\mathbf{P}^{\top})(\mathbf{P}^{\top})^{\infty}|| <= \epsilon$

Выведите полученную матрицу на экран.

- [X] Проверено на семинаре

In [21]:
P_inf = np.linalg.matrix_power(P.T, 1000)

In [22]:
e = 0.00001
np.linalg.norm(P_inf - np.dot(P.T, P_inf)) <= e

True

In [23]:
P_inf

array([[0.1025641 , 0.1025641 , 0.1025641 , ..., 0.1025641 , 0.1025641 ,
        0.1025641 ],
       [0.05769231, 0.05769231, 0.05769231, ..., 0.05769231, 0.05769231,
        0.05769231],
       [0.06410256, 0.06410256, 0.06410256, ..., 0.06410256, 0.06410256,
        0.06410256],
       ...,
       [0.03846154, 0.03846154, 0.03846154, ..., 0.03846154, 0.03846154,
        0.03846154],
       [0.07692308, 0.07692308, 0.07692308, ..., 0.07692308, 0.07692308,
        0.07692308],
       [0.10897436, 0.10897436, 0.10897436, ..., 0.10897436, 0.10897436,
        0.10897436]])

<p class="task" id="4"></p>

4\. Cоздайте вектор начального состояния $\mathbf{p}^0 = [0, ..., 1]^T $. Получите стационарное состояние $\mathbf{p}^\infty$, воспользовавшись полученной матрицей $(\mathbf{P}^{\top})^\infty$. Решите задачу двумя способами: при помощи матричного умножения и при помощи оператора индексации.

Используя функцию `np.allclose`, покажите, что векторы стационарных состояний, полученные двумя разными методами, совпадают (с точностью до тысячных).

- [ ] Проверено на семинаре

In [51]:
p_0 = np.zeros(len(G))
p_0[-1] = 1

In [52]:
P_inf = np.linalg.matrix_power(P.T, 1000)

In [53]:
p_inf_1 = P_inf.dot(p_0) #матричное умножение

In [54]:
p_inf_2 = P_inf[:, -1] #индексация

In [55]:
np.allclose(p_inf_1, p_inf_2, atol=0.001)


True

<p class="task" id="5"></p>

5\. Напишите функцию `generate_walk`, которая принимает на вход граф `G`, начальный узел `node` и генерирует случайное блуждание длины `walk_len`, начинающееся с этого узла. Сгенерируйте несколько реализаций (не меньше 1000) случайных блужданий длины 10 с началом в узле 7 и выясните, в каком узле случайные блуждания заканчиваются чаще всего. Выведите номер этого узла на экран.

- [ ] Проверено на семинаре

In [26]:
def generate_walk(G, node, walk_len):
    # ...
    return walk

In [27]:
import random

In [41]:
def generate_walk(G, node, walk_len):
    walk = [node]
    current_node = node
    for _ in range(walk_len - 1):
        neighbors = list(G.neighbors(current_node))
        if neighbors:
            next_node = random.choice(neighbors)
            walk.append(next_node)
            current_node = next_node
        else:
            break
    return walk

In [42]:
G = nx.karate_club_graph()

In [43]:
node_counts = {}

In [44]:
for _ in range(1500):
    end_node = generate_walk(G, 7, 10)[-1]
    if end_node in node_counts:
        node_counts[end_node] += 1
    else:
        node_counts[end_node] = 1

In [45]:
node = max(node_counts, key=node_counts.get)

In [46]:
node

0